---
title: Stream.readStringUntil()
---




= readStringUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`readStringUntil()` reads characters from a stream into a string. The function terminates if the terminator character is detected or it times out (see link:../streamsettimeout[setTimeout()]).

This function is part of the Stream class, and is called by any class that inherits from it (Wire, Serial, etc). See the link:../../stream[Stream class] main page for more information.
[%hardbreaks]


[float]
=== Syntax
`stream.readStringUntil(terminator)`


[float]
=== Parameters
`terminator` : the character to search for (`char`)

[float]
=== Returns
The entire string read from a stream, until the terminator character is detected.  (`String`)
The terminator character is read and removed from the stream, but not included in the returned string.
Everything eventually following the terminator character stays in the stream for future reading.


--
// OVERVIEW SECTION ENDS
